---
title: "R Notebook"
output: html_notebook
---

W województwie pomorskim też jest informacja o ogniskach ale wyłącznie w postaci tekstu

http://www.wsse.gda.pl/aktualnosci-i-komunikaty/aktualnosci/1661-raport-z-dnia-13-pazdziernika-2020-roku-na-temat-sars-cov-2-w-wojewodztwie-pomorskim

Przykładowo:

```
Pomorski Państwowy Wojewódzki Inspektor Sanitarny informuje o sytuacji w ogniskach zakażenia wirusem Sars-CoV-2 w województwie pomorskim:

1.Ognisko związane z weselem w powiecie gdańskim, szkołą w powiecie kościerskim, zakładem pracy w powiecie kartuskim – 28 przypadków zakażenia, w tym 7 pracowników.
2.Ognisko związane z DPS – 91 przypadków zakażenia w tym 49 przypadków zakażenia wśród pensjonariuszy i 16 przypadków zakażenia wśród personelu, 26 przypadków zakażenia u innych osób związanych z tym ogniskiem, powiat bytowski.
3.Ognisko związane z imprezami urodzinowymi (uczniowie LO) – 33 przypadki zakażenia w tym 22 uczniów, miasto Gdynia, miasto Sopot, powiat tczewski, powiat pucki, powiat wejherowski.
4.Ognisko związane ze Szpitalem – 13 przypadków zakażenia, w tym 6 pracowników, powiat pucki.
5.Ognisko związane ze Szkołą i Kościołem – 84 przypadki zakażenia, w tym 11 nauczycieli, 34 uczniów, miasto Słupsk, powiat słupski
```


```{r}
library(tidyverse)
library(rvest)
library(httr)
library(stringi)
library(lubridate)
library(readxl)
library(pdftools)
library(scales)
Sys.setlocale("LC_TIME", "pl_PL.UTF-8")
```


```{r}
aktualnosci <- paste0("http://www.wsse.gda.pl/aktualnosci-i-komunikaty/aktualnosci?start=", seq(0,1100,10))
```



# Szkoły -- raporty

```{r}
get_links_school <- function(url) {
  url %>%  GET() %>%  read_html() %>%  html_nodes("div.page-header.with-date") -> szkola_links 
  szkola_links %>% html_text() %>% str_detect("szkół") %>% which() -> szkola_which
  szkola_links[szkola_which] %>% html_nodes('a') %>% html_attr("href") %>% paste0("http://www.wsse.gda.pl",.) -> szkola_links
  return(szkola_links)
}

szkola_linki <- lapply(aktualnosci, get_links_school)
szkola_linki <- unlist(szkola_linki)
szkola_linki <- szkola_linki[str_detect(szkola_linki, "informacje-dotyczace-szkol")]

``` 

```{r}
get_links_school_content <- function(url) {
  url %>% read_html() -> szkola_doc

data.frame(data = szkola_doc %>% html_node("div.additional-infos")  %>% html_text(), 
           wnioski =  szkola_doc %>% html_nodes("div.itemFullText > p") %>% html_text() %>% str_c(collapse = " ") %>%
             stri_extract_first_regex("\\d{1,5} wniosków") %>% str_extract("\\d+"),
           nauczyciele_covid = szkola_doc %>% html_nodes("div.itemFullText > p") %>% html_text() %>% str_c(collapse = " ") %>%
             stri_extract_first_regex("(wynosi|u) \\d{1,5}") %>% str_extract("\\d+"),
           uczniowie_covid = szkola_doc %>% html_nodes("div.itemFullText > p") %>% html_text() %>% str_c(collapse = " ") %>%
             stri_extract_last_regex("(wynosi|u) \\d{1,5}") %>% str_extract("\\d+"),
           uczniowie_kwar = szkola_doc %>% html_nodes("div.itemFullText > p") %>% html_text() %>% str_c(collapse = " ") %>%
             stri_extract_last_regex("\\d{1,5} uczniów") %>% str_extract("\\d+"),
           nauczyciele_kwar = szkola_doc %>% html_nodes("div.itemFullText > p") %>% html_text() %>% str_c(collapse = " ") %>%
             stri_extract_last_regex("\\d{1,5} nauczycieli") %>% str_extract("\\d+"),
           stringsAsFactors = FALSE,
           url = url )  -> df
return(df)
}

szkoly_df <- lapply(szkola_linki, get_links_school_content) %>%
  bind_rows() %>%
  mutate_at(vars(wnioski:nauczyciele_kwar), as.numeric) %>%
  select(-url) %>%
  mutate(data = str_extract(data, "\\d{1,2} (wrzesień|październik) 2020"),
         data = str_replace(data, " październik ", "-10-"),
         data = str_replace(data, " wrzesień ", "-09-"),
         data = dmy(data))  %>%
  mutate(nauczyciele_covid2=ifelse(data <= as.Date("2020-09-10"), uczniowie_covid, nauczyciele_covid),
         uczniowie_covid2=ifelse(data <= as.Date("2020-09-10"), nauczyciele_covid, uczniowie_covid)) %>%
  select(-uczniowie_covid, -nauczyciele_covid) %>%
  rename(nauczyciele_covid=nauczyciele_covid2,
         uczniowie_covid=uczniowie_covid2)
```


Liczba osób na kwarantannie

```{r}
kwar_pliki <- paste0("http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_", format(szkoly_df$data, "%d_%m_%Y"), ".pdf")

get_stats_pomorkie <- function(pdf_file) {
  
  pdf_plik <- pdf_text(pdf_file) %>%
  str_replace_all("\\n", "X") %>% 
  str_replace_all("\\s+", " X ") 
  
  kwarantanna <- pdf_plik[2] %>%
  str_extract("X \\d{1,5} X \\d{1,5}X") %>%
  str_extract("\\d{1,5}X$") %>%
  str_extract("\\d{1,5}") %>%
  as.numeric()
  
  przypadki <- pdf_plik[1] %>%
  stri_extract_first_regex("X \\d{1,5} X") %>%
  str_extract("\\d{1,5}") %>%
  as.numeric()
  
  return(c(kwarantanna, przypadki))
}

liczba_kwar <- lapply(kwar_pliki, get_stats_pomorkie)
liczba_kwar <- do.call("rbind", liczba_kwar)


```

Łączymy przypadki oraz dane o uczniach i nauczycielach

```{r}
szkoly_df %>%
  select(data, nauczyciele_covid, uczniowie_covid, uczniowie_kwar, nauczyciele_kwar) %>%
  mutate(przypadki_kwar = liczba_kwar[,1],
         przypadki_sum = liczba_kwar[,2]) %>%
  arrange(data) %>%
  mutate(p_uczniowie = uczniowie_covid/przypadki_sum,
         p_nauczyciele = nauczyciele_covid/przypadki_sum,
         p_razem = (nauczyciele_covid+uczniowie_covid)/przypadki_sum,
         k_uczniowie = uczniowie_kwar/przypadki_kwar,
         k_nauczyciele = nauczyciele_kwar/przypadki_kwar,
         k_razem = (nauczyciele_kwar+uczniowie_kwar)/przypadki_kwar) %>%
  select(data, p_uczniowie:k_razem) %>%
  gather(stat, val, -data) %>%
  separate(stat, c("typ", "kto"), "_") %>%
  mutate(typ = ifelse(typ == "k", "Objęci kwarantanną", "Potwierdzone przypadki SARS-CoV-2"),
         kto = factor(kto, 
                      c("uczniowie", "nauczyciele", "razem"),
                      c("uczniowie", "nauczyciele", "razem"),
                      ordered = T)) %>%
  ggplot(data = ., aes(x = data, y = val, color = kto)) +
  geom_line() +
  facet_wrap(~typ) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) + 
  scale_color_brewer(type = "qual", name = "Grupa", palette = "Set1") + 
  theme_bw() + 
  labs(x = "Dzień", y = "Odsetek",
       title = 
       "Udział uczniów, nauczycieli i tych grup razem we wszystkich osobach objętych kwarantanną i z potwierdzonym SARS-CoV-2\nw Województwie Pomorskim (stan na 14.10.2020)",
       subtitle = "Opracowanie na podstawie dziennych raportów Wojewódzkiej Stacji Sanitarno-Epidemiologicznej w Gdansku",
       caption = 
       "Źródło: Opracowanie własne na podstawie WSSE w Gdańsku Kody i dane dostępne są na https://github.com/BERENZ/covid-roznosci. Wszelkie błędy są po mojej stronie (@mberesewicz)")  -> p
  

ggsave(plot = p, filename = "../figs/szkoly-pomorskie.png", width = 12, height = 6)

```


Zapis danych z wykresu

```{r}
szkoly_df %>%
  select(data, nauczyciele_covid, uczniowie_covid, uczniowie_kwar, nauczyciele_kwar) %>%
  mutate(przypadki_kwar = liczba_kwar[,1],
         przypadki_sum = liczba_kwar[,2]) %>%
  arrange(data) %>%
  mutate(p_uczniowie = uczniowie_covid/przypadki_sum,
         p_nauczyciele = nauczyciele_covid/przypadki_sum,
         p_razem = (nauczyciele_covid+uczniowie_covid)/przypadki_sum,
         k_uczniowie = uczniowie_kwar/przypadki_kwar,
         k_nauczyciele = nauczyciele_kwar/przypadki_kwar,
         k_razem = (nauczyciele_kwar+uczniowie_kwar)/przypadki_kwar)  -> dane_wykres

write_csv(x = dane_wykres, path = "../data/szkoly-pomorskie.csv")
```

# Ogniska

```{r}
aktualnosci <- paste0("http://www.wsse.gda.pl/aktualnosci-i-komunikaty/aktualnosci?start=", seq(0,1100,10))
```

Raporty

```{r}
get_links_reports <- function(url) {
  url %>%  GET() %>%  read_html() %>%  html_nodes("div.page-header.with-date") -> reports_links 
  reports_links %>% html_text() %>% str_detect("Raport z dnia") %>% which() -> reports_which
  reports_links[reports_which] %>% html_nodes('a') %>% html_attr("href") %>% paste0("http://www.wsse.gda.pl",.) -> reports_links
  return(reports_links)
}

reports_linki <- lapply(aktualnosci, get_links_reports)
reports_linki <- unlist(reports_linki)
reports_linki <- reports_linki[str_detect(reports_linki, "raport-z-dnia")]
```

```{r}

get_reports_details <- function(url) {
  print(url)
  
  url %>%
  GET() %>%
  content() %>%
  html_nodes("div.itemFullText > ol > li") %>%
  html_text() %>%
  .[stri_detect(., fixed = "Ognisko")] -> wsse_gdansk
  
  ## drugi sposób zapisu
  if (length(wsse_gdansk) == 0) {
     url %>%
      GET() %>%
      content() %>%
      html_nodes("div.itemFullText > p") %>%
      html_text() %>%
      .[stri_detect(., regex = "\\d{1,2}.+Ognisko")] %>%
      stri_split(., regex = "\\.\\d{1,2}") %>%
      unlist() %>%
      stri_replace_first_regex("^.+Ognisko", "Ognisko") -> wsse_gdansk
  }
  
  ## trzeci sposób zapisu
  if (length(wsse_gdansk) == 0) {
    url %>%
      GET() %>%
      content() %>%
      html_nodes("div.itemFullText > ul > li") %>%
      html_text() %>%
      .[stri_detect(., regex = "Ognisko|ognisko")] -> wsse_gdansk
    
  }
  ## czwarty sposób zapisu
 if (length(wsse_gdansk) == 0) {
    url %>%
      GET() %>%
      content() %>%
      html_nodes("div.itemFullText > p") %>%
      html_text() %>%
      .[stri_detect(., regex = "Ognisko|ognisko")] %>%
      stri_replace_first_regex("^.+ognisko", "Ognisko")-> wsse_gdansk
    
  }
  
  df <- data.frame(
    data = url %>% GET() %>% content() %>% html_node("div.additional-infos")  %>% html_text(),
    ognisko_typ = stri_split_regex(wsse_gdansk, ".?(–|-).?", n = 2, simplify = T)[, 1] %>% stri_trans_tolower()  %>% stri_replace_first_regex("ognisko związane (z|ze) ", ""),
    liczba = stri_extract_first_regex(wsse_gdansk,
      "\\d{1,3}.{1,3}(przypadki|przypadek|przypadków|przepadki|osoby|osób)"
    ) %>% stri_extract(regex = "\\d+") %>% as.numeric(),
    stringsAsFactors = F
  )

return(df)
}

gdansk_df <- lapply(reports_linki[1:144], get_reports_details)

gdansk_df_all <- bind_rows(gdansk_df) %>% 
  mutate(data = str_extract(data, "\\d{1,2} (maj|czerwiec|lipiec|sierpień|wrzesień|październik) 2020"),
         data = str_replace(data, " październik ", "-10-"),
         data = str_replace(data, " wrzesień ", "-09-"),
         data = str_replace(data, " sierpień ", "-08-"),
         data = str_replace(data, " lipiec ", "-07-"),
         data = str_replace(data, " czerwiec ", "-06-"),
         data = str_replace(data, " maj ", "-05-"),
         data = dmy(data))
```

W ilu przypadkach mamy informacje o ognisku


```{r}
kwar_pliki <- paste0("http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_", format(unique(gdansk_df_all$data), "%d_%m_%Y"), ".pdf")

kwar_pliki[which(kwar_pliki=="http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_04_10_2020.pdf")] <- 
  "http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_04_10_2020.pdf.pdf"

kwar_pliki[which(kwar_pliki=="http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_17_08_2020.pdf")] <- 
  "http://www.wsse.gda.pl/media/k2/attachments/Covid_17_08.pdf"

kwar_pliki[which(kwar_pliki=="http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_13_06_2020.pdf")] <- 
  "http://www.wsse.gda.pl/media/k2/attachments/covid-19_mapa_13_06_2020_2.pdf"


statystyki_pomorskie <- lapply(kwar_pliki[-1], get_stats_pomorkie)
statystyki_pomorskie_df <- do.call("rbind", statystyki_pomorskie)
statystyki_pomorskie_df <- data.frame(statystyki_pomorskie_df)
```



```{r}
gdansk_df_all %>%
  count(data, wt = liczba) %>%
  filter(data != "2020-10-15") %>% 
  mutate(total = rev(statystyki_pomorskie_df[, 2])) %>%
  ggplot(data = ., aes(x = data, y = n/total)) + geom_line() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) + 
  labs(x = "Data", y = "Odsetek", 
       title = "Odsetek przypadków COVID-19 z potwierdzonego ogniska według WSSE Gdańsk (Pomorskie)")
```


